<?
$aMenuLinks = Array(
    Array(
        "Анкета",
        "/backoffice/contractors/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Мои заказы",
        "/backoffice/contractors/orders/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Отзывы",
        "/backoffice/contractors/reviews/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Мои статьи",
        "/backoffice/contractors/articles/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Статистика",
        "/backoffice/contractors/statistic/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Баллы",
        "/backoffice/contractors/points/",
        Array(),
        Array("ADDITIONAL"=>true),
        ""
    ),
    Array(
        "Акции",
        "/backoffice/contractors/sales/",
        Array(),
        Array("ADDITIONAL"=>true),
        ""
    ),
    /*Array(
        "Новости",
        "/news/",
        Array(),
        Array("ADDITIONAL"=>true),
        ""
    ),*/
    Array(
        "Служба поддержки",
        "/backoffice/contractors/help/",
        Array(),
        Array("ADDITIONAL"=>true),
        ""
    ),
    /*Array(
        "-Сервисы от портала",
        "/backoffice/contractors/services/",
        Array(),
        Array("ADDITIONAL"=>true),
        ""
    )*/
);
