<?
$aMenuLinks = Array(
    Array(
        "Анкета",
        "/backoffice/vendors/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Мероприятия",
        "/backoffice/vendors/events/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Обучение",
        "/backoffice/vendors/educations/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Статьи",
        "/backoffice/vendors/articles/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "-Статистика",
        "/backoffice/vendors/statistic/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Акции",
        "/backoffice/vendors/sales/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "-Комментарии",
        "/backoffice/vendors/comments/",
        Array(),
        Array("ADDITIONAL"=>true),
        ""
    ),
    Array(
        "Служба поддержки",
        "/backoffice/vendors/help/",
        Array(),
        Array("ADDITIONAL"=>true),
        ""
    )
);
